/* ==========================================================================
   AMAYA ERP — Printable documents
   ========================================================================== */

const Docs = {};

/** Documents accept either a record id or the record itself. */
function docRecord(col, input, keys) {
  if (!input) return null;
  if (typeof input === 'object') return input;
  const ks = keys || ['id'];
  return DB.get(col).find(r => ks.some(k => r[k] === input)) || null;
}

function companyHeader(title, sub, metaLines) {
  const s = state.db.settings;
  return `<div class="doc-head">
    <div class="co">
      <img class="doc-logo" src="${BRAND.logo}" alt="${esc(BRAND.legalName)}">
      <h1>${esc(s.company || APP.name)}</h1>
      <div>${esc(s.address || '')}</div>
      <div>${esc(s.phone || '')} ${s.email ? ' · ' + esc(s.email) : ''}</div>
      ${s.taxNo ? `<div>Tax / Trade licence: ${esc(s.taxNo)}</div>` : ''}
    </div>
    <div class="meta">
      ${(metaLines || []).map(l => `<div>${l}</div>`).join('')}
    </div>
  </div>
  <div class="doc-title">${esc(title)}</div>
  ${sub ? `<div style="text-align:center;font-size:11px;color:#555;margin:-10px 0 14px">${sub}</div>` : ''}`;
}
function docSigs(blocks) {
  return `<div class="doc-sigs">${blocks.map(b => `<div class="doc-sig"><b>${esc(b.title)}</b>${b.lines.map(l => `<div>${l}</div>`).join('')}</div>`).join('')}</div>`;
}
function docFooter(note) {
  return `<div class="doc-foot">${esc(note || state.db.settings.footerNote || '')}<br>Generated by ${esc(APP.name)} v${APP.version} on ${esc(fmtDateTime(nowISO()))}</div>`;
}
function openDocument(html, title) {
  openModal({
    width: 'xl', autofocus: false,
    title: title || 'Document preview',
    sub: 'A4 · use “Print” for a paper copy or “Save as PDF” in the print dialog.',
    body: `<div class="doc" id="printDoc">${html}</div>`,
    foot: `<button class="btn" data-cancel>Close</button><button class="btn primary" data-print>🖨 Print / Save PDF</button>`,
    onMount(el) {
      qs('[data-print]', el).onclick = () => printDocument();
    }
  });
}
function printDocument() {
  $$('.page').forEach(p => p.classList.remove('print-active'));
  const doc = $('printDoc');
  if (!doc) return;
  /* Clone into a print root so @media print rules apply cleanly */
  let root = $('printRoot');
  if (!root) { root = document.createElement('div'); root.id = 'printRoot'; root.className = 'print-root'; document.body.appendChild(root); }
  root.innerHTML = doc.outerHTML;
  root.style.cssText = 'position:fixed;left:-10000px;top:0;width:820px;background:#fff;';
  setTimeout(() => {
    window.print();
    setTimeout(() => { root.innerHTML = ''; root.style.cssText = ''; }, 800);
  }, 120);
}

/* ------------------------------------------------------- Gate pass */
Docs.gatePass = function (ref) {
  const t = docRecord('transfers', ref, ['transferRef', 'id']) || DB.get('transfers')[0];
  if (!t) return toast('No transfer available to print', 'warn');
  const html = `
    ${companyHeader('Transfer Manifest / Gate Pass', 'Authorised inter-facility stock movement', [
      `<strong>MANIFEST #</strong> ${esc(t.transferRef)}`,
      `Date: ${esc(fmtDate(t.date))}`,
      `Status: <strong>${esc(t.status)}</strong>`
    ])}
    <div class="doc-parties">
      <div><b>Origin facility (dispatch from)</b>${esc(t.fromLocation)}<br><span style="color:#555">Authorised by: ${esc(t.approvedBy || t.requestedBy || '—')}</span></div>
      <div><b>Destination facility (receive at)</b>${esc(t.toLocation)}<br><span style="color:#555">Carrier: ${esc(t.carrier || 'Internal fleet')}</span></div>
    </div>
    <table class="doc-table">
      <thead><tr><th style="width:34px">#</th><th>SKU / Model</th><th>Colour</th><th>Facility from</th><th class="r">Quantity</th><th class="r">Checked</th></tr></thead>
      <tbody>
        ${(t.items || []).map((it, i) => `<tr>
          <td>${i + 1}</td><td><strong>${esc(it.sku)}</strong></td><td>${esc(it.color || '—')}</td>
          <td>${esc(t.fromLocation)}</td><td class="r"><strong>${fmt(it.qty)}</strong></td><td class="r"></td>
        </tr>`).join('')}
        <tr class="total"><td colspan="4">TOTAL UNITS</td><td class="r">${fmt(t.totalUnits)}</td><td class="r"></td></tr>
      </tbody>
    </table>
    ${(t.tracking ? `<div class="doc-note"><strong>Tracking:</strong> ${esc(t.tracking)}</div>` : '')}
    ${(t.imeis && t.imeis.length ? `<div class="doc-note"><strong>Itemised serial / IMEI registry:</strong><br><span style="font-family:monospace;word-break:break-all">${t.imeis.map(i => esc(typeof i === 'string' ? i : i.imei)).join(', ')}</span></div>` : '')}
    ${(t.notes ? `<div class="doc-note"><strong>Notes:</strong> ${esc(t.notes)}</div>` : '')}
    ${docSigs([
      { title: 'Dispatched by (signature)', lines: [`Name: ${esc(t.dispatchedBy || t.requestedBy || '________________')}`, 'Date &amp; time: __________________'] },
      { title: 'Transport / carrier', lines: [`Name: ${esc(t.carrier || '________________')}`, 'Vehicle / AWB: ______________'] },
      { title: 'Received &amp; verified by (signature)', lines: [`Name: ${esc(t.receivedBy || '________________')}`, 'Date &amp; time: __________________'] }
    ])}
    ${docFooter('Stock leaving this facility is only authorised against a signed gate pass. Retain the receiver copy for reconciliation.')}`;
  openDocument(html, `Gate pass · ${t.transferRef}`);
  audit('PRINT', 'Transfers', t.transferRef, 'Gate pass generated');
};

/* --------------------------------------------------------- Job card */
Docs.jobCard = function (id) {
  const r = docRecord('repairs', id) || DB.get('repairs')[0];
  if (!r) return toast('No repair ticket available to print', 'warn');
  const payable = num(r.cost) + num(r.labourCost) - num(r.discount);
  const html = `
    ${companyHeader('Service Job Card', 'After-sales intake, diagnosis and recovery record', [
      `<strong>TICKET #</strong> ${esc(r.ticketNo)}`,
      `Intake: ${esc(fmtDate(r.intakeDate))}`,
      `Status: <strong>${esc(r.status)}</strong>`
    ])}
    <div class="doc-parties">
      <div><b>Device</b>${esc(r.model)} ${esc(r.color || '')}<br>
        IMEI: <span style="font-family:monospace">${esc(r.imei || '—')}</span><br>
        IMEI 2: <span style="font-family:monospace">${esc(r.imei2 || '—')}</span><br>
        Serial: <span style="font-family:monospace">${esc(r.serialNumber || '—')}</span></div>
      <div><b>Customer</b>${esc(r.customerName || '—')}<br>${esc(r.customerPhone || '')}<br>
        <b>Technician:</b> ${esc(r.technician || 'Unassigned')}<br>
        <b>Warranty:</b> ${r.warrantyClaim ? 'Manufacturer claim' : 'Chargeable'}</div>
    </div>
    <table class="doc-table">
      <thead><tr><th>Step</th><th>Detail</th><th class="r">Amount</th></tr></thead>
      <tbody>
        <tr><td>Defect category</td><td>${esc(r.defectType)}</td><td class="r">—</td></tr>
        <tr><td>Promised date</td><td>${esc(fmtDate(r.promisedDate))}</td><td class="r">—</td></tr>
        <tr><td>Parts consumed</td><td>As per diagnosis</td><td class="r">${money(r.cost)}</td></tr>
        <tr><td>Labour</td><td>Workshop time</td><td class="r">${money(r.labourCost)}</td></tr>
        <tr><td>Discount</td><td>Goodwill / warranty adjustment</td><td class="r">−${money(r.discount)}</td></tr>
        <tr class="total"><td colspan="2">PAYABLE</td><td class="r">${money(payable)}</td></tr>
      </tbody>
    </table>
    <div class="doc-note"><strong>Reported symptoms &amp; diagnosis:</strong><br>${esc(r.notes || '—')}</div>
    <table class="doc-table">
      <thead><tr><th style="width:50%">Stage</th><th>Date</th><th>Signature</th></tr></thead>
      <tbody>
        <tr><td>Received at counter</td><td>${esc(fmtDate(r.intakeDate))}</td><td></td></tr>
        <tr><td>Diagnosed by technician</td><td>${r.completedDate ? esc(fmtDate(r.completedDate)) : ''}</td><td></td></tr>
        <tr><td>Ready / returned to customer</td><td>${esc(fmtDate(r.completedDate || ''))}</td><td></td></tr>
      </tbody>
    </table>
    ${docSigs([
      { title: 'Customer signature', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Technician signature', lines: [`Name: ${esc(r.technician || '________________')}`, 'Date: ______________________'] },
      { title: 'Service counter stamp', lines: ['', ''] }
    ])}
    ${docFooter('Devices not collected within 60 days of the promised date may be disposed of against this job card.')}`;
  openDocument(html, `Job card · ${r.ticketNo}`);
  audit('PRINT', 'After-Sales', r.ticketNo, 'Job card generated');
};

/* ---------------------------------------------------------- Invoice */
Docs.invoice = function (id) {
  /* Accept a sales id, an invoice id, or an invoice number */
  let sale = null, inv = null;
  const found = (typeof id === 'object' && id) ? id
    : DB.get('sales').find(s => s.id === id || s.orderId === id || s.invoiceNo === id);
  if (found) sale = found;
  else {
    inv = DB.get('invoices').find(i => i.id === id || i.invoiceNo === id);
    if (inv) sale = DB.get('sales').find(s => s.id === inv.refId) || null;
  }
  if (!sale && !inv) return toast('No invoice found for that reference', 'warn');
  if (!sale && inv) {
    const html = simpleInvoice(inv);
    openDocument(html, `Invoice · ${inv.invoiceNo}`);
    return;
  }
  const due = new Date(); due.setDate(due.getDate() + 21);
  const html = `
    ${companyHeader('Tax Invoice', 'Retail &amp; trade sale', [
      `<strong>INVOICE #</strong> ${esc(sale.invoiceNo)}`,
      `Order: ${esc(sale.orderId)}`,
      `Date: ${esc(fmtDate(sale.date))}`,
      `Due: ${esc(fmtDate(due.toISOString().slice(0, 10)))}`
    ])}
    <div class="doc-parties">
      <div><b>Billed to</b>${esc(sale.customerName)}<br>${esc(sale.customerPhone || '')}</div>
      <div><b>Dispatched from</b>${esc(sale.warehouse || 'Main House')}<br>Sold by: ${esc(sale.user || '—')}</div>
    </div>
    <table class="doc-table">
      <thead><tr><th style="width:34px">#</th><th>Item description</th><th>Colour</th><th class="r">Qty</th><th class="r">Unit price</th><th class="r">Amount</th></tr></thead>
      <tbody>
        ${(sale.items || []).map((it, i) => `<tr>
          <td>${i + 1}</td><td><strong>${esc(it.sku)}</strong></td><td>${esc(it.color || '—')}</td>
          <td class="r">${fmt(it.qty)}</td><td class="r">${money(it.price)}</td><td class="r">${money(num(it.qty) * num(it.price))}</td>
        </tr>`).join('')}
        <tr><td colspan="5" class="r">Subtotal</td><td class="r">${money(sale.subtotal)}</td></tr>
        ${num(sale.discount) ? `<tr><td colspan="5" class="r">Discount</td><td class="r">−${money(sale.discount)}</td></tr>` : ''}
        ${num(sale.tax) ? `<tr><td colspan="5" class="r">Tax</td><td class="r">${money(sale.tax)}</td></tr>` : ''}
        <tr class="total"><td colspan="5" class="r">GRAND TOTAL</td><td class="r">${money(sale.total)}</td></tr>
      </tbody>
    </table>
    <div class="doc-parties" style="grid-template-columns:1fr 1fr">
      <div><b>Payment</b>${esc(sale.paymentMethod)}<br>Status: <strong>${esc(sale.status)}</strong></div>
      <div><b>Amount in words</b>${esc(numberWords(sale.total))}</div>
    </div>
    ${sale.note ? `<div class="doc-note"><strong>Note:</strong> ${esc(sale.note)}</div>` : ''}
    ${docSigs([
      { title: 'Customer signature', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'For the company', lines: [`Name: ${esc(sale.user || '________________')}`, 'Date: ______________________'] }
    ])}
    ${docFooter('This is a computer-generated invoice. Goods once sold are exchangeable only against this document within 7 days.')}`;
  openDocument(html, `Invoice · ${sale.invoiceNo}`);
  audit('PRINT', 'Sales', sale.orderId, `Invoice ${sale.invoiceNo} generated`);
};
function simpleInvoice(inv) {
  const due = num(inv.amount) - num(inv.paid);
  return `
    ${companyHeader('Invoice', inv.type === 'Purchase' ? 'Supplier bill' : 'Service charge', [
      `<strong>INVOICE #</strong> ${esc(inv.invoiceNo)}`,
      `Date: ${esc(fmtDate(inv.date))}`,
      `Due: ${esc(fmtDate(inv.dueDate))}`,
      `Status: <strong>${esc(inv.status)}</strong>`
    ])}
    <div class="doc-parties">
      <div><b>${inv.type === 'Purchase' ? 'Supplier' : 'Customer'}</b>${esc(inv.partyName)}</div>
      <div><b>Settlement</b>Paid: ${money(inv.paid)}<br>Outstanding: <strong>${money(due)}</strong></div>
    </div>
    <table class="doc-table">
      <thead><tr><th>Description</th><th class="r">Amount</th></tr></thead>
      <tbody>
        <tr><td>${esc(inv.type)} invoice ${esc(inv.invoiceNo)}${inv.notes ? ' — ' + esc(inv.notes) : ''}</td><td class="r">${money(inv.amount)}</td></tr>
        <tr><td class="r">Settled to date</td><td class="r">${money(inv.paid)}</td></tr>
        <tr class="total"><td class="r">BALANCE DUE</td><td class="r">${money(due)}</td></tr>
      </tbody>
    </table>
    ${docSigs([
      { title: 'Issued by', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Accepted by', lines: ['Name: ____________________', 'Date: ______________________'] }
    ])}
    ${docFooter()}`;
}

function numberWords(v) {
  const n = Math.round(num(v));
  if (!isFinite(n)) return '';
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const two = x => x < 20 ? ones[x] : tens[Math.floor(x / 10)] + (x % 10 ? ' ' + ones[x % 10] : '');
  const three = x => `${two(Math.floor(x / 100))} Hundred${x % 100 ? ' ' + two(x % 100) : ''}`;
  const chunk = (n, scale) => {
    if (n === 0) return '';
    const s = String(n).padStart(3, '0');
    const parts = [];
    const h = Number(s[0]), t = Number(s.slice(1));
    if (h) parts.push(ones[h] + ' Hundred');
    if (t) parts.push(two(t));
    return parts.join(' ') + (scale ? ' ' + scale : '');
  };
  if (n === 0) return 'Zero';
  const scales = [[1e9, 'Billion'], [1e6, 'Million'], [1e3, 'Thousand'], [1, '']];
  let out = [], rem = n;
  for (const [val, name] of scales) {
    const c = Math.floor(rem / val);
    if (c > 0) { out.push(chunk(c, name)); rem %= val; }
  }
  return out.join(' ').trim() + ' ' + CURRENCY() + ' only';
}

/* ------------------------------------------------------ Purchase order */
Docs.purchaseOrder = function (id) {
  const p = docRecord('purchases', id, ['id', 'poNumber']) || DB.get('purchases')[0];
  if (!p) return toast('No purchase order available to print', 'warn');
  const sup = DB.byId('suppliers', p.supplierId);
  const html = `
    ${companyHeader('Purchase Order', 'Authorised procurement request', [
      `<strong>PO #</strong> ${esc(p.poNumber)}`,
      `Date: ${esc(fmtDate(p.date))}`,
      `Expected: ${esc(fmtDate(p.eta))}`,
      `Status: <strong>${esc(p.status)}</strong>`
    ])}
    <div class="doc-parties">
      <div><b>Supplier</b>${esc(p.supplier)}<br>${esc(sup ? sup.phone : '')} ${sup && sup.email ? '<br>' + esc(sup.email) : ''}
        ${sup ? `<br>Account: ${esc(sup.accountNo || '—')}` : ''}</div>
      <div><b>Deliver to</b>${esc(p.house || 'Main House')}<br>Approved by: ${esc(p.approvedBy || '—')}
        <br>Terms: ${esc(sup ? sup.paymentTerms : '—')}</div>
    </div>
    <table class="doc-table">
      <thead><tr><th style="width:34px">#</th><th>Item</th><th>Category</th><th class="r">Qty</th><th class="r">Unit cost</th><th class="r">Line total</th></tr></thead>
      <tbody>
        <tr><td>1</td><td><strong>${esc(p.item)}</strong></td><td>${esc(p.type || '')}</td>
          <td class="r">${fmt(p.qty)}</td><td class="r">${money(p.cost)}</td><td class="r">${money(p.total)}</td></tr>
        <tr class="total"><td colspan="3">ORDER TOTAL</td><td class="r">${fmt(p.qty)}</td><td class="r"></td><td class="r">${money(p.total)}</td></tr>
      </tbody>
    </table>
    <div class="doc-note"><strong>Terms:</strong> Delivery must match the ordered specification. Report any discrepancy within 48 hours of receipt.
      ${p.notes ? `<br><strong>Notes:</strong> ${esc(p.notes)}` : ''}
      <br><strong>Received so far:</strong> ${fmt(p.receivedQty)} of ${fmt(p.qty)} units.</div>
    ${docSigs([
      { title: 'Requested by', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Approved by', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Supplier acknowledgement', lines: ['Name: ____________________', 'Date: ______________________'] }
    ])}
    ${docFooter('This purchase order is valid only against the company header above.')}`;
  openDocument(html, `Purchase order · ${p.poNumber}`);
  audit('PRINT', 'Purchases', p.poNumber, 'Purchase order generated');
};

/* ------------------------------------------------- Delivery challan */
Docs.deliveryChallan = function (id) {
  const d = docRecord('dispatches', id, ['id', 'dispatchId']) || DB.get('dispatches')[0];
  if (!d) return toast('No dispatch available to print', 'warn');
  const sale = d.saleId ? DB.byId('sales', d.saleId) : null;
  const rows = sale ? (sale.items || []) : [{ sku: d.items || 'Mixed consignment', qty: 1, price: 0, color: '' }];
  const html = `
    ${companyHeader('Delivery Challan', 'Outbound consignment document', [
      `<strong>DISPATCH #</strong> ${esc(d.dispatchId)}`,
      `Order: ${esc(d.orderId || '—')}`,
      `Date: ${esc(fmtDate(d.date))}`,
      `ETA: ${esc(fmtDate(d.eta))}`,
      `Status: <strong>${esc(d.status)}</strong>`
    ])}
    <div class="doc-parties">
      <div><b>Deliver to</b>${esc(d.customer)}<br>${esc(d.phone || '')}<br>Route: ${esc(d.route || '—')}</div>
      <div><b>Carried by</b>${esc(d.courier)}<br>Tracking: <span style="font-family:monospace">${esc(d.tracking || '—')}</span><br>
        Dispatched by: ${esc(d.dispatchedBy || '—')}</div>
    </div>
    <table class="doc-table">
      <thead><tr><th style="width:34px">#</th><th>Item</th><th>Colour</th><th class="r">Qty</th><th class="r">Delivered</th></tr></thead>
      <tbody>
        ${rows.map((it, i) => `<tr><td>${i + 1}</td><td><strong>${esc(it.sku)}</strong></td>
          <td>${esc(it.color || '—')}</td><td class="r">${fmt(it.qty)}</td><td class="r"></td></tr>`).join('')}
        <tr class="total"><td colspan="3">TOTAL UNITS</td><td class="r">${fmt(sum(rows, r => r.qty))}</td><td class="r"></td></tr>
      </tbody>
    </table>
    <div class="doc-parties" style="grid-template-columns:1fr 1fr">
      <div><b>Consignment value</b>${sale ? money(sale.total) : '—'}<br>Weight: ${num(d.weight)} kg<br>Delivery charge: ${money(d.cost)}</div>
      <div><b>Payment</b>${sale ? esc(sale.paymentMethod) : '—'}<br>Invoice: ${sale ? esc(sale.invoiceNo) : '—'}</div>
    </div>
    ${d.notes ? `<div class="doc-note"><strong>Handling notes:</strong> ${esc(d.notes)}</div>` : ''}
    ${docSigs([
      { title: 'Packed by', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Courier / driver signature', lines: ['Name: ____________________', 'Vehicle: _______________'] },
      { title: 'Received by (customer)', lines: ['Name: ____________________', 'Date: ______________________'] }
    ])}
    ${docFooter('Goods must be checked against this challan at the point of receipt. Report shortages within 24 hours.')}`;
  openDocument(html, `Delivery challan · ${d.dispatchId}`);
  audit('PRINT', 'Dispatch', d.dispatchId, 'Delivery challan generated');
};

/* ------------------------------------------------------------ Payslip */
Docs.payslip = function (id) {
  const p = docRecord('payroll', id) || DB.get('payroll')[0];
  if (!p) return toast('No payslip available to print', 'warn');
  const emp = DB.byId('employees', p.employeeId);
  const gross = num(p.baseSalary) + num(p.overtimeHours) * num(p.overtimeRate) + num(p.bonus);
  const html = `
    ${companyHeader('Payslip', 'Monthly salary statement', [
      `<strong>${esc(monthLabel(p.month))}</strong>`,
      `Employee: ${esc(p.code || '')}`,
      `Status: <strong>${esc(p.status)}</strong>`,
      p.paidDate ? `Paid: ${esc(fmtDate(p.paidDate))}` : 'Unpaid'
    ])}
    <div class="doc-parties">
      <div><b>Employee</b>${esc(p.employeeName)}<br>${emp ? esc(emp.designation || emp.role) : ''}<br>${emp ? esc(emp.department) : ''}<br>${emp ? esc(emp.location) : ''}</div>
      <div><b>Statement</b>Base: ${money(p.baseSalary)}<br>Overtime: ${num(p.overtimeHours)} h × ${money(p.overtimeRate)}<br>
        Bonus: ${money(p.bonus)}<br>Deductions: −${money(p.deductions)}</div>
    </div>
    <table class="doc-table">
      <thead><tr><th>Component</th><th class="r">Amount</th></tr></thead>
      <tbody>
        <tr><td>Basic salary</td><td class="r">${money(p.baseSalary)}</td></tr>
        <tr><td>Overtime (${num(p.overtimeHours)} hours @ ${money(p.overtimeRate)})</td><td class="r">${money(num(p.overtimeHours) * num(p.overtimeRate))}</td></tr>
        ${num(p.bonus) ? `<tr><td>Bonus / incentive</td><td class="r">${money(p.bonus)}</td></tr>` : ''}
        <tr class="total"><td>GROSS EARNINGS</td><td class="r">${money(gross)}</td></tr>
        ${num(p.deductions) ? `<tr><td>Deductions</td><td class="r">−${money(p.deductions)}</td></tr>` : ''}
        <tr class="total"><td>NET PAYABLE</td><td class="r">${money(p.netSalary)}</td></tr>
      </tbody>
    </table>
    <div class="doc-note"><strong>In words:</strong> ${esc(numberWords(p.netSalary))}</div>
    ${docSigs([
      { title: 'Employee signature', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Accounts / payroll', lines: ['Name: ____________________', 'Date: ______________________'] }
    ])}
    ${docFooter('This is a computer-generated payslip. Please report any discrepancy within 7 days.')}`;
  openDocument(html, `Payslip · ${p.employeeName} · ${p.month}`);
  audit('PRINT', 'Payroll', p.id, `Payslip generated for ${p.employeeName}`);
};

/* -------------------------------------------------------- Stock report */
Docs.stockReport = function () {
  const inv = sortBy(DB.get('inventory'), l => l.house);
  const html = `
    ${companyHeader('Stock Valuation Report', 'Physical stock valued at landed cost', [
      `Generated: ${esc(fmtDateTime(nowISO()))}`,
      `Facilities: ${DB.get('locations').length}`,
      `Lines: ${inv.length}`,
      `Total units: <strong>${fmt(totalUnits())}</strong>`
    ])}
    <table class="doc-table">
      <thead><tr><th>SKU / Model</th><th>Brand</th><th>Type</th><th>Facility</th><th>Colour</th><th class="r">Open</th><th class="r">In</th><th class="r">Out</th><th class="r">Sold</th><th class="r">Adj</th><th class="r">Available</th><th class="r">Value</th></tr></thead>
      <tbody>
        ${inv.map(l => `<tr>
          <td><strong>${esc(l.sku)}</strong></td><td>${esc(l.brand)}</td><td>${esc(l.type)}</td>
          <td>${esc(l.house)}</td><td>${esc(l.color)}</td>
          <td class="r">${fmt(l.openingQty)}</td><td class="r">${fmt(l.inQty)}</td>
          <td class="r">${fmt(l.outQty)}</td><td class="r">${fmt(l.soldQty)}</td>
          <td class="r">${fmt(l.adjustedQty)}</td>
          <td class="r"><strong>${fmt(inHand(l))}</strong></td><td class="r">${money(lineValue(l))}</td>
        </tr>`).join('')}
        <tr class="total"><td colspan="10">TOTAL INVENTORY VALUE</td><td class="r">${fmt(totalUnits())}</td><td class="r">${money(inventoryValue())}</td></tr>
      </tbody>
    </table>
    ${docSigs([
      { title: 'Prepared by', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Verified by', lines: ['Name: ____________________', 'Date: ______________________'] },
      { title: 'Approved by', lines: ['Name: ____________________', 'Date: ______________________'] }
    ])}
    ${docFooter('This valuation is generated from the live ledger. A physical count is required to confirm.')}`;
  openDocument(html, 'Stock valuation report');
  audit('PRINT', 'Reports', 'stock', 'Stock valuation report generated');
};

/* -------------------------------------------------------- Audit report */
Docs.auditReport = function () {
  const log = DB.get('audit').slice(0, 400);
  const html = `
    ${companyHeader('Audit Log Extract', 'Accountability trail', [
      `Generated: ${esc(fmtDateTime(nowISO()))}`,
      `Events shown: <strong>${log.length}</strong>`,
      `Total retained: ${DB.get('audit').length}`
    ])}
    <table class="doc-table">
      <thead><tr><th>Timestamp</th><th>User</th><th>Role</th><th>Action</th><th>Module</th><th>Reference</th><th>Detail</th></tr></thead>
      <tbody>
        ${log.map(a => `<tr>
          <td>${esc(fmtDateTime(a.timestamp))}</td><td>${esc(a.user)}</td><td>${esc(a.role || '—')}</td>
          <td><strong>${esc(a.action)}</strong></td><td>${esc(a.module)}</td>
          <td style="font-family:monospace">${esc(a.recordId || '—')}</td><td>${esc(a.details || '—')}</td>
        </tr>`).join('')}
      </tbody>
    </table>
    ${docFooter('This extract is a point-in-time copy of the accountability trail.')}`;
  openDocument(html, 'Audit log extract');
  audit('PRINT', 'Audit', 'extract', 'Audit extract generated');
};

/* ---------------------------------------------------------- Data sheet */
Docs.dataSheet = function () {
  const s = state.db.settings;
  const html = `
    ${companyHeader('System Data Sheet', 'Configuration, facilities and volumes', [
      `Generated: ${esc(fmtDateTime(nowISO()))}`,
      `Version: ${APP.version}`
    ])}
    <div class="doc-parties">
      <div><b>Configuration</b>Low-stock threshold: ${esc(s.threshold)}<br>Shift start: ${esc(s.shiftStart)}<br>
        Backend: ${esc(s.backendMode)}<br>Auto-sync: ${s.autoSync ? 'on' : 'off'}</div>
      <div><b>Access</b>Accounts: ${DB.get('users').length}<br>Roles: ${ROLES.length}<br>
        Active session: ${state.session ? esc(state.session.user.email) : '—'}</div>
    </div>
    <table class="doc-table">
      <thead><tr><th>Collection</th><th class="r">Records</th><th>Collection</th><th class="r">Records</th></tr></thead>
      <tbody>
        ${(() => {
          const rows = DB.collections.map(c => [c, DB.get(c).length]);
          const half = Math.ceil(rows.length / 2);
          const a = rows.slice(0, half), b = rows.slice(half);
          return a.map((r, i) => `<tr><td>${esc(r[0])}</td><td class="r">${fmt(r[1])}</td>
            <td>${b[i] ? esc(b[i][0]) : ''}</td><td class="r">${b[i] ? fmt(b[i][1]) : ''}</td></tr>`).join('');
        })()}
      </tbody>
    </table>
    <div class="section-title" style="margin-top:16px">Facilities</div>
    <table class="doc-table">
      <thead><tr><th>Name</th><th>Type</th><th>Address</th><th class="r">Units held</th><th class="r">Value</th></tr></thead>
      <tbody>
        ${DB.get('locations').map(l => {
          const lines = DB.get('inventory').filter(x => x.house === l.name);
          return `<tr><td><strong>${esc(l.name)}</strong></td><td>${esc(l.type || '')}</td><td>${esc(l.address || '')}</td>
            <td class="r">${fmt(sum(lines, inHand))}</td><td class="r">${money(sum(lines, lineValue))}</td></tr>`;
        }).join('')}
      </tbody>
    </table>
    ${docFooter('Confidential — internal system document.')}`;
  openDocument(html, 'System data sheet');
};
